import assert from 'node:assert/strict';
import test from 'node:test';
import type { Session, User } from '@supabase/supabase-js';
import { createIdentityRuntime, type IdentityAuthClient } from '../../src/features/auth/identityRuntime.ts';
import { identityErrorState, resolveAuthenticatedIdentity, signedOutIdentityState } from '../../src/features/auth/identityResolutionService.ts';
import type { IdentityState } from '../../src/features/auth/identityRuntimeTypes.ts';

const user = (id: string) => ({ id } as User);
const session = (id: string) => ({ user: user(id) } as Session);
const ready = (id: string): IdentityState => ({ status: 'authenticated_ready', user: user(`auth-${id}`), profile: { id: `profile-${id}`, authUserId: `auth-${id}`, username: id, displayName: id === 'lars' ? 'Lars' : 'Lore', role: 'child', childKey: id as 'lars' | 'lore' }, mainCollection: { id: `collection-${id}`, profileId: `profile-${id}`, name: id, type: 'main', createdAt: 'now', updatedAt: 'now' }, message: `Welkom, ${id}.` });
const waitFor = async (predicate: () => boolean) => { for (let attempt = 0; attempt < 50; attempt += 1) { if (predicate()) return; await new Promise((resolve) => setTimeout(resolve, 0)); } throw new Error('Runtime state werd niet op tijd bereikt.'); };

function authClient(initialSession: Session | null, initialError: unknown = null) {
  let callback: ((event: string, session: Session | null) => void) | null = null;
  let unsubscribeCount = 0;
  const client: IdentityAuthClient = { auth: { async getSession() { return { data: { session: initialSession }, error: initialError }; }, onAuthStateChange(next) { callback = next; return { data: { subscription: { unsubscribe() { unsubscribeCount += 1; } } } }; } } };
  return { client, emit(next: Session | null) { callback?.(next ? 'SIGNED_IN' : 'SIGNED_OUT', next); }, get unsubscribeCount() { return unsubscribeCount; } };
}

const resolver = async (authUser: User) => ready(authUser.id.replace('auth-', ''));
const successfulLogout = async () => ({ ok: true, message: 'Uitgelogd.' });

test('initialization without a session becomes signed_out', async () => { const auth = authClient(null); const runtime = createIdentityRuntime(auth.client, resolver, successfulLogout); runtime.start(); await waitFor(() => runtime.getState().status === 'signed_out'); assert.deepEqual(runtime.getState(), signedOutIdentityState()); runtime.dispose(); });
test('initialization with a session resolves authenticated_ready', async () => { const auth = authClient(session('auth-lars')); const runtime = createIdentityRuntime(auth.client, resolver, successfulLogout); runtime.start(); await waitFor(() => runtime.getState().status === 'authenticated_ready'); assert.equal(runtime.getState().profile?.displayName, 'Lars'); assert.equal(runtime.getState().mainCollection?.id, 'collection-lars'); runtime.dispose(); });
test('getSession error becomes a cleared error state', async () => { const auth = authClient(null, new Error('session failed')); const runtime = createIdentityRuntime(auth.client, resolver, successfulLogout); runtime.start(); await waitFor(() => runtime.getState().status === 'error'); assert.deepEqual(runtime.getState(), identityErrorState()); runtime.dispose(); });
test('auth-state change moves signed-out runtime to authenticated', async () => { const auth = authClient(null); const runtime = createIdentityRuntime(auth.client, resolver, successfulLogout); runtime.start(); await waitFor(() => runtime.getState().status === 'signed_out'); auth.emit(session('auth-lore')); await waitFor(() => runtime.getState().status === 'authenticated_ready'); assert.equal(runtime.getState().profile?.displayName, 'Lore'); runtime.dispose(); });
test('account switch clears Lars before publishing Lore', async () => { const auth = authClient(session('auth-lars')); const states: IdentityState[] = []; const runtime = createIdentityRuntime(auth.client, resolver, successfulLogout); runtime.subscribe((state) => states.push(state)); runtime.start(); await waitFor(() => runtime.getState().profile?.displayName === 'Lars'); auth.emit(session('auth-lore')); assert.equal(runtime.getState().status, 'authenticated_profile_loading'); assert.equal(runtime.getState().profile, null); assert.equal(runtime.getState().mainCollection, null); await waitFor(() => runtime.getState().profile?.displayName === 'Lore'); assert.equal(states.at(-1)?.mainCollection?.id, 'collection-lore'); runtime.dispose(); });
test('a stale Lars resolution cannot override newer Lore state', async () => { const auth = authClient(null); let releaseLars!: (state: IdentityState) => void; const runtime = createIdentityRuntime(auth.client, (authUser) => authUser.id === 'auth-lars' ? new Promise((resolve) => { releaseLars = resolve; }) : Promise.resolve(ready('lore')), successfulLogout); runtime.start(); await waitFor(() => runtime.getState().status === 'signed_out'); auth.emit(session('auth-lars')); await waitFor(() => typeof releaseLars === 'function'); auth.emit(session('auth-lore')); await waitFor(() => runtime.getState().profile?.displayName === 'Lore'); releaseLars(ready('lars')); await new Promise((resolve) => setTimeout(resolve, 0)); assert.equal(runtime.getState().profile?.displayName, 'Lore'); runtime.dispose(); });
test('logout clears user, profile and collection before logout completes', async () => { const auth = authClient(session('auth-lars')); let finish!: (result: { ok: boolean; message: string }) => void; const runtime = createIdentityRuntime(auth.client, resolver, () => new Promise((resolve) => { finish = resolve; })); runtime.start(); await waitFor(() => runtime.getState().status === 'authenticated_ready'); const pending = runtime.signOut(); assert.deepEqual(runtime.getState(), signedOutIdentityState()); finish({ ok: true, message: 'Uitgelogd.' }); await pending; runtime.dispose(); });
test('logout failure retains no personal state', async () => { const auth = authClient(session('auth-lars')); const runtime = createIdentityRuntime(auth.client, resolver, async () => ({ ok: false, message: 'Mislukt.' })); runtime.start(); await waitFor(() => runtime.getState().status === 'authenticated_ready'); await runtime.signOut(); assert.deepEqual(runtime.getState(), identityErrorState()); runtime.dispose(); });
test('dispose unsubscribes from auth changes and prevents stale completion', async () => { const auth = authClient(session('auth-lars')); let release!: (state: IdentityState) => void; const runtime = createIdentityRuntime(auth.client, () => new Promise((resolve) => { release = resolve; }), successfulLogout); runtime.start(); await waitFor(() => runtime.getState().status === 'authenticated_profile_loading'); runtime.dispose(); assert.equal(auth.unsubscribeCount, 1); release(ready('lars')); await new Promise((resolve) => setTimeout(resolve, 0)); assert.equal(runtime.getState().status, 'authenticated_profile_loading'); });

function resolutionClient(profile: unknown, collection: unknown) { const calls: Array<{ table: string; filters: Array<[string, unknown]> }> = []; return { calls, from(table: string) { const call = { table, filters: [] as Array<[string, unknown]> }; calls.push(call); const query = { select() { return query; }, eq(column: string, value: unknown) { call.filters.push([column, value]); return query; }, async maybeSingle() { return { data: table === 'profiles' ? profile : collection, error: null }; } }; return query; } }; }
test('resolution uses exact auth_user_id and verified main collection', async () => { const client = resolutionClient({ id: 'profile-lore', auth_user_id: 'auth-lore', username: 'lore', display_name: 'Lore', role: 'child', child_key: 'lore' }, { id: 'collection-lore', profile_id: 'profile-lore', name: 'Lore', type: 'main', created_at: 'now', updated_at: 'now' }); const state = await resolveAuthenticatedIdentity(client as never, user('auth-lore')); assert.equal(state.status, 'authenticated_ready'); assert.deepEqual(client.calls[0].filters, [['auth_user_id', 'auth-lore']]); assert.deepEqual(client.calls[1].filters, [['profile_id', 'profile-lore'], ['type', 'main']]); });
