import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { identityErrorState, resolveAuthenticatedIdentity, signedOutIdentityState } from '../../src/features/auth/identityResolutionService.ts';
function clientWith(profile: unknown, collection: unknown, profileError: unknown = null, collectionError: unknown = null) {
  const calls: Array<{ table: string; filters: Array<[string, unknown]> }> = [];
  return { calls, from(table: string) { const call = { table, filters: [] as Array<[string, unknown]> }; calls.push(call); const query = { select() { return query; }, eq(column: string, value: unknown) { call.filters.push([column, value]); return query; }, async maybeSingle() { return table === 'profiles' ? { data: profile, error: profileError } : { data: collection, error: collectionError }; } }; return query; } };
}
const user = { id: 'auth-lore' } as never;
const profile = { id: 'profile-lore', auth_user_id: 'auth-lore', username: 'lore', display_name: 'Lore', role: 'child', child_key: 'lore' };
const collection = { id: 'collection-lore', profile_id: 'profile-lore', name: 'Lore', type: 'main', created_at: 'now', updated_at: 'now' };
test('login retains validation and delegates successful credentials to Supabase Auth', () => { const boundary = readFileSync('src/features/auth/loginActionBoundary.ts', 'utf8'); const service = readFileSync('src/features/auth/authLoginService.ts', 'utf8'); assert.match(boundary, /if \(!username && !password\)/); assert.match(boundary, /if \(!password\)/); assert.match(service, /signInWithPassword/); assert.match(service, /Login mislukt/); });
test('authenticated identity resolves the exact auth_user_id profile and its main collection', async () => { const client = clientWith(profile, collection); const state = await resolveAuthenticatedIdentity(client as never, user); assert.equal(state.status, 'authenticated_ready'); assert.equal(state.profile?.displayName, 'Lore'); assert.equal(state.mainCollection?.id, 'collection-lore'); assert.deepEqual(client.calls[0].filters, [['auth_user_id', 'auth-lore']]); assert.deepEqual(client.calls[1].filters, [['profile_id', 'profile-lore'], ['type', 'main']]); });
test('authenticated identity exposes missing-profile without collection lookup', async () => { const client = clientWith(null, collection); const state = await resolveAuthenticatedIdentity(client as never, user); assert.equal(state.status, 'authenticated_profile_missing'); assert.equal(state.profile, null); assert.equal(state.mainCollection, null); assert.equal(client.calls.length, 1); });
test('resolution fails closed for mismatched profile, ambiguous errors, or missing main collection', async () => { assert.equal((await resolveAuthenticatedIdentity(clientWith({ ...profile, auth_user_id: 'auth-lars' }, collection) as never, user)).status, 'error'); assert.equal((await resolveAuthenticatedIdentity(clientWith(null, null, new Error('multiple rows')) as never, user)).status, 'error'); assert.equal((await resolveAuthenticatedIdentity(clientWith(profile, null) as never, user)).status, 'error'); });
test('signed-out and error transitions clear every personal identity field', () => { for (const state of [signedOutIdentityState(), identityErrorState()]) { assert.equal(state.user, null); assert.equal(state.profile, null); assert.equal(state.mainCollection, null); } });
test('provider initializes from session, subscribes centrally, and clears before signOut completes', () => { const source = readFileSync('src/features/auth/IdentityProvider.tsx', 'utf8'); assert.match(source, /auth\.getSession\(\)/); assert.match(source, /auth\.onAuthStateChange/); assert.match(source, /publish\(signedOutIdentityState\(\)\);\s*setIsSigningOut\(true\);\s*const result = await logout\(\)/s); });
