import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient } from '@supabase/supabase-js';
import { PINNED_DATASET_VERSION, validateLocalDatasetCheckout } from './local-checkout.ts';
import { reportHash } from './catalog-report-identity.ts';
import { parseManifest, parseSourceSets } from './catalog-quality-audit.ts';

const APPROVAL = 'apply-catalog-set-metadata';
type PlanRow = { setCatalogId: string; databaseSetCode: string; sourceSetCode: string; identity: string; action: string; changedFields: Record<string, unknown>; blockReason: string | null };
type ApprovedReport = { phase?: string; mode?: string; runnerStatus?: string; status?: string; datasetVersion?: string; databaseWritesTotal?: number; reportHash?: string; summary?: { plannedMetadataUpdates?: number; blockedRows?: number }; plan?: PlanRow[] };
type SourceSet = { name: string; series: string; releaseDate: string; printedTotal: number; total: number; symbolUrl: string; logoUrl: string };
type DatabaseSet = { id: string; set_code: string; name: string; source: string | null; source_id: string | null; series: string | null; release_date: string | null; printed_total: number | null; total: number | null; symbol_url: string | null; logo_url: string | null };
function date(v: string | null) { return (v ?? '').replaceAll('/', '-'); }
function args(v: string[]) { if (v.length !== 10 || v[0] !== '--mode' || !['write','idempotency'].includes(v[1]) || v[2] !== '--input-root' || v[4] !== '--approved-report' || v[6] !== '--confirm-write' || v[8] !== '--report' || v[7] !== APPROVAL) throw new Error(`Gebruik --mode <write|idempotency> --input-root <dataset> --approved-report <rapport> --confirm-write ${APPROVAL} --report <nieuw rapport>.`); return { mode:v[1], inputRoot:resolve(v[3]), approved:resolve(v[5]), report:resolve(v[9]) }; }
function parseApproved(path: string): ApprovedReport { const raw=JSON.parse(readFileSync(path,'utf8')) as ApprovedReport; if (raw.reportHash !== reportHash(raw) || raw.phase !== 'Catalog set metadata dry-run' || raw.mode !== 'read-only' || raw.runnerStatus !== 'PASS' || raw.status !== 'REVIEW_REQUIRED' || raw.datasetVersion !== PINNED_DATASET_VERSION || raw.databaseWritesTotal !== 0 || raw.summary?.plannedMetadataUpdates !== 161 || raw.summary?.blockedRows !== 0 || !Array.isArray(raw.plan)) throw new Error('Goedgekeurd dry-runrapport is ongeldig of wijkt af.'); return raw; }
async function main() {
  const o=args(process.argv.slice(2)); if(existsSync(o.report)) throw new Error(`Rapport bestaat al: ${o.report}`); validateLocalDatasetCheckout(o.inputRoot,PINNED_DATASET_VERSION); const approved=parseApproved(o.approved);
  const manifest=parseManifest(JSON.parse(readFileSync('config/catalog/local-pokemon-tcg-data-manifest.json','utf8'))); const sourceSets=parseSourceSets(JSON.parse(readFileSync(join(o.inputRoot,'sets/en.json'),'utf8')),manifest) as Map<string,SourceSet>;
  const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('SUPABASE_URL en SUPABASE_SERVICE_ROLE_KEY ontbreken.');const c=createClient(url,key);
  const plan=approved.plan!.filter(x=>x.action==='update_metadata'); const ids=plan.map(x=>x.setCatalogId); const {data,error}=await c.from('sets_catalog').select('id,set_code,name,source,source_id,series,release_date,printed_total,total,symbol_url,logo_url').in('id',ids);if(error||!data||data.length!==161)throw new Error('Exacte set-precheck mislukt.');
  const rows=(data as DatabaseSet[]).map(s=>{const p=plan.find(x=>x.setCatalogId===s.id)!;const src=sourceSets.get(p.sourceSetCode);if(!src||s.name!==src.name||(p.identity==='exact_set_code'&&s.set_code!==p.sourceSetCode)||(p.identity==='exact_legacy_source_id'&&(s.source!=='pokemon_tcg_api'||s.source_id!==p.sourceSetCode)))throw new Error(`${s.id}: identiteit wijkt af.`);return {id:s.id,expected_series:s.series,expected_release_date:s.release_date,expected_printed_total:s.printed_total,expected_total:s.total,expected_symbol_url:s.symbol_url,expected_logo_url:s.logo_url,series:src.series,release_date:src.releaseDate,printed_total:src.printedTotal,total:src.total,symbol_url:src.symbolUrl,logo_url:src.logoUrl};});
  const needed=rows.filter(r=>r.expected_series!==r.series||date(r.expected_release_date)!==date(r.release_date)||r.expected_printed_total!==r.printed_total||r.expected_total!==r.total||r.expected_symbol_url!==r.symbol_url||r.expected_logo_url!==r.logo_url);
  let writes=0;if(o.mode==='write'&&needed.length){const {data:rpc,error:rpcError}=await c.rpc('apply_catalog_set_metadata',{p_rows:needed});if(rpcError||rpc!==needed.length)throw new Error('Transactionele metadata-write mislukt.');writes=rpc;}
  if(o.mode==='write'&&needed.length===0) throw new Error('Write abort: geen resterende metadata-acties; gebruik idempotency.');
  const {data:after,error:afterError}=await c.from('sets_catalog').select('id,set_code,name,source,source_id,series,release_date,printed_total,total,symbol_url,logo_url').in('id',ids);if(afterError||!after||after.length!==161)throw new Error('Postcheck-read mislukt.');
  for(const s of after as DatabaseSet[]){const p=plan.find(x=>x.setCatalogId===s.id)!;const src=sourceSets.get(p.sourceSetCode)!;if(s.name!==src.name||s.series!==src.series||date(s.release_date)!==date(src.releaseDate)||s.printed_total!==src.printedTotal||s.total!==src.total||s.symbol_url!==src.symbolUrl||s.logo_url!==src.logoUrl)throw new Error(`${s.id}: exacte metadata-postcheck mislukt.`);}
  const report={schemaVersion:1,phase:'Catalog set metadata write',mode:o.mode,approvedReportHash:approved.reportHash,datasetVersion:PINNED_DATASET_VERSION,plannedRows:161,databaseWritesTotal:writes,status:'PASS',reportHash:''};report.reportHash=reportHash(report);mkdirSync(dirname(o.report),{recursive:true});writeFileSync(o.report,`${JSON.stringify(report,null,2)}\n`);console.log(`Catalog set metadata ${o.mode}: PASS; rows=161; databaseWritesTotal=${writes}; reportHash=${report.reportHash}`);
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(e=>{console.error(e instanceof Error?e.message:'Metadata write failed.');process.exitCode=1;});
