import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient } from '@supabase/supabase-js';
import { loadPokemonTcgDataJson } from './local-json.ts';
import { PINNED_DATASET_VERSION, validateLocalDatasetCheckout } from './local-checkout.ts';
import { reportHash } from './catalog-report-identity.ts';
import { parseManifest } from './catalog-quality-audit.ts';
type M={setId:string;jsonPath:string;expectedCards:number;enabled:boolean}; type Card={id:string;external_source:string|null;external_id:string|null;pokemon:string;set_name:string;set_code:string|null;number:string}; type Ref={card_catalog_id:string;source:string;external_id:string};
function args(a:string[]){if(a.length!==4||a[0]!=='--input-root'||a[2]!=='--report')throw new Error('Gebruik uitsluitend --input-root <dataset> --report <nieuw rapport>.');return{root:resolve(a[1]),report:resolve(a[3])};}
function sourceMap(root:string,sets:M[]){const map=new Map<string,string>();for(const s of sets){const x=loadPokemonTcgDataJson(join(root,s.jsonPath),s.setId);if(x.cards.length!==s.expectedCards)throw new Error(`${s.setId}: kaartenaantal wijkt af.`);for(const c of x.cards){if(!c.id||map.has(c.id))throw new Error(`${s.setId}: ongeldige bronidentiteit.`);map.set(c.id,s.setId);}}return map;}
export function classify(cards:Card[],refs:Ref[],source:Map<string,string>){const byCard=new Map<string,Ref[]>();for(const r of refs){const v=byCard.get(r.card_catalog_id)??[];v.push(r);byCard.set(r.card_catalog_id,v);}return cards.map(c=>{const ids=[c.external_id,...(byCard.get(c.id)??[]).filter(r=>r.source==='pokemon_tcg_api').map(r=>r.external_id)].filter((v):v is string=>!!v);const targets=[...new Set(ids.map(id=>source.get(id)).filter((v):v is string=>!!v))];return{id:c.id,pokemon:c.pokemon,number:c.number,externalSource:c.external_source,externalIds:ids,classification:targets.length===1?'exact_source_candidate':targets.length===0?'missing_source_identity':'ambiguous_source_identity',targetSetCode:targets.length===1?targets[0]:null};});}
async function main(){const o=args(process.argv.slice(2));if(existsSync(o.report))throw new Error(`Rapport bestaat al: ${o.report}`);validateLocalDatasetCheckout(o.root,PINNED_DATASET_VERSION);const manifest=parseManifest(JSON.parse(readFileSync('config/catalog/local-pokemon-tcg-data-manifest.json','utf8'))) as M[];const source=sourceMap(o.root,manifest);const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('SUPABASE_URL en SUPABASE_SERVICE_ROLE_KEY ontbreken.');const c=createClient(url,key);const {data:cards,error}=await c.from('cards_catalog').select('id,external_source,external_id,pokemon,set_name,set_code,number').is('set_code',null);if(error||!cards)throw new Error('Null-set kaarten read mislukt.');const ids=cards.map(x=>x.id);const {data:refs,error:re}=await c.from('card_external_references').select('card_catalog_id,source,external_id').in('card_catalog_id',ids);if(re||!refs)throw new Error('Reference-read mislukt.');const result=classify(cards as Card[],refs as Ref[],source);const report={schemaVersion:1,phase:'Catalog null set-code analysis',mode:'read-only',datasetVersion:PINNED_DATASET_VERSION,databaseWritesTotal:0,status:'ACTION_REQUIRED',summary:{nullSetCards:result.length,exactSourceCandidates:result.filter(x=>x.classification==='exact_source_candidate').length,missingSourceIdentity:result.filter(x=>x.classification==='missing_source_identity').length,ambiguousSourceIdentity:result.filter(x=>x.classification==='ambiguous_source_identity').length},results:result,reportHash:''};report.reportHash=reportHash(report);mkdirSync(dirname(o.report),{recursive:true});writeFileSync(o.report,`${JSON.stringify(report,null,2)}\n`);console.log(`Catalog null set-code analysis: ACTION_REQUIRED; cards=${result.length}; databaseWritesTotal=0; reportHash=${report.reportHash}`);}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(e=>{console.error(e instanceof Error?e.message:'Null-set analysis failed.');process.exitCode=1;});
