import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient } from '@supabase/supabase-js';
import { PINNED_DATASET_VERSION } from './local-checkout.ts';

const SOURCE = 'pokemon_tcg_api';
const EXPECTED_PAIRS = 36;
const SET_IDS = ['swsh10tg', 'swsh11tg', 'swsh12pt5gg', 'swsh12tg', 'swsh9tg', 'swshp'];
type Mode = 'dry-run' | 'write' | 'idempotency';
type Card = { id: string; external_source: string | null; external_id: string | null; pokemon: string; set_name: string | null; set_code: string | null; number: string | null; rarity: string | null; image_small: string | null; image_large: string | null; card_details: Record<string, unknown> | null; created_at: string };
type Ref = { id: string; card_catalog_id: string; source: string; external_id: string };
type PlanRow = { legacy_id: string; duplicate_id: string; external_id: string; pokemon: string; set_name: string; set_code: string; number: string; rarity: string | null; image_small: string | null; image_large: string | null; card_details: Record<string, unknown> };
type Report = { schemaVersion: 1; phase: 'Phase 7B recover six legacy duplicates'; mode: Mode; datasetVersion: string; repairPlan: PlanRow[]; repairPlanHash: string; reportHash: string; expectedPairs: number; plannedDatabaseWrites: number; databaseWritesTotal: number; status: 'PASS' | 'FAIL'; errors: string[] };

function canonical(value: unknown): string { if (value === null || typeof value !== 'object') return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(',')}}`; }
function hash(value: unknown): string { return createHash('sha256').update(canonical(value), 'utf8').digest('hex'); }
function isEmptyDetails(value: Record<string, unknown> | null): boolean { return value !== null && !Array.isArray(value) && Object.keys(value).length === 0; }

export function createRepairPlan(cards: Card[], refs: Ref[], collectionCounts: Map<string, number>): PlanRow[] {
  const grouped = new Map<string, Card[]>();
  for (const card of cards) { if (!card.set_code || !card.number || !SET_IDS.includes(card.set_code)) continue; const key = `${card.set_code}\u0000${card.number}\u0000${card.pokemon}`; const rows = grouped.get(key) ?? []; rows.push(card); grouped.set(key, rows); }
  const plan: PlanRow[] = [];
  for (const rows of grouped.values()) {
    if (rows.length === 1) continue;
    if (rows.length !== 2) throw new Error('Herstel geblokkeerd: onveilige duplicaatgroep.');
    const legacy = rows.find((row) => row.external_source === 'legacy_public_cards');
    const duplicate = rows.find((row) => row.external_source === SOURCE);
    if (!legacy || !duplicate || !legacy.set_name || !legacy.set_code || !legacy.number || !duplicate.external_id || !duplicate.card_details || !isEmptyDetails(legacy.card_details) || legacy.pokemon !== duplicate.pokemon || legacy.set_name !== duplicate.set_name || legacy.set_code !== duplicate.set_code || legacy.number !== duplicate.number || legacy.rarity !== duplicate.rarity || legacy.image_small !== duplicate.image_small || legacy.image_large !== duplicate.image_large || collectionCounts.get(legacy.id) !== 1 || (collectionCounts.get(duplicate.id) ?? 0) !== 0) throw new Error('Herstel geblokkeerd: legacy- of collectieprecheck wijkt af.');
    const legacyRefs = refs.filter((ref) => ref.card_catalog_id === legacy.id); const duplicateRefs = refs.filter((ref) => ref.card_catalog_id === duplicate.id);
    if (legacyRefs.length !== 1 || duplicateRefs.length !== 1 || legacyRefs[0].source !== SOURCE || duplicateRefs[0].source !== SOURCE || duplicateRefs[0].external_id !== duplicate.external_id || legacyRefs[0].external_id !== duplicate.external_id.toLowerCase()) throw new Error('Herstel geblokkeerd: externe reference wijkt af.');
    plan.push({ legacy_id: legacy.id, duplicate_id: duplicate.id, external_id: duplicate.external_id, pokemon: duplicate.pokemon, set_name: duplicate.set_name!, set_code: duplicate.set_code!, number: duplicate.number!, rarity: duplicate.rarity, image_small: duplicate.image_small, image_large: duplicate.image_large, card_details: duplicate.card_details });
  }
  plan.sort((a, b) => a.external_id.localeCompare(b.external_id));
  if (plan.length !== EXPECTED_PAIRS || new Set(plan.map((row) => row.legacy_id)).size !== EXPECTED_PAIRS || new Set(plan.map((row) => row.duplicate_id)).size !== EXPECTED_PAIRS) throw new Error('Herstel geblokkeerd: niet exact 36 bewezen paren.');
  return plan;
}

function parseArgs(argv: string[]) { const values = new Map<string, string>(); for (let i = 0; i < argv.length; i += 2) { if (!['--mode', '--report', '--approved-report', '--confirm-write'].includes(argv[i]) || !argv[i + 1]) throw new Error('Ongeldige argumenten.'); values.set(argv[i], argv[i + 1]); } const mode = values.get('--mode') as Mode; if (!['dry-run', 'write', 'idempotency'].includes(mode) || !values.get('--report')) throw new Error('Gebruik --mode dry-run|write|idempotency --report <nieuw rapport>.'); if ((mode === 'write' || mode === 'idempotency') && !values.get('--approved-report')) throw new Error('Write en idempotency vereisen --approved-report.'); if (mode === 'write' && values.get('--confirm-write') !== 'phase-7b-recover-six-legacy-duplicates') throw new Error('Write vereist de exacte bevestiging.'); return { mode, reportPath: resolve(values.get('--report')!), approvedReport: values.get('--approved-report') ? resolve(values.get('--approved-report')!) : undefined }; }
function writeReport(path: string, report: Omit<Report, 'reportHash'>): Report { mkdirSync(dirname(path), { recursive: true }); const complete = { ...report, reportHash: hash(report) }; writeFileSync(path, `${JSON.stringify(complete, null, 2)}\n`); return complete; }
function readApproved(path: string): Report { const report = JSON.parse(readFileSync(path, 'utf8')) as Report; const { reportHash, ...body } = report; if (report.schemaVersion !== 1 || report.mode !== 'dry-run' || report.status !== 'PASS' || report.databaseWritesTotal !== 0 || reportHash !== hash(body) || report.datasetVersion !== PINNED_DATASET_VERSION || report.expectedPairs !== EXPECTED_PAIRS || report.repairPlanHash !== hash(report.repairPlan)) throw new Error('Goedgekeurd herstelrapport is ongeldig.'); return report; }
async function snapshot(client: ReturnType<typeof createClient>) { const { data: cards, error: cardError } = await client.from('cards_catalog').select('id,external_source,external_id,pokemon,set_name,set_code,number,rarity,image_small,image_large,card_details,created_at').in('set_code', SET_IDS); if (cardError || !cards) throw new Error('Cards snapshot mislukt.'); const ids = (cards as Card[]).map((card) => card.id); const [{ data: refs, error: refError }, { data: links, error: linkError }] = await Promise.all([client.from('card_external_references').select('id,card_catalog_id,source,external_id').in('card_catalog_id', ids), client.from('collection_cards').select('card_catalog_id').in('card_catalog_id', ids)]); if (refError || linkError) throw new Error('Reference- of collectieprecheck mislukt.'); const counts = new Map<string, number>(); for (const row of links ?? []) counts.set(row.card_catalog_id as string, (counts.get(row.card_catalog_id as string) ?? 0) + 1); return { cards: cards as Card[], refs: (refs ?? []) as Ref[], counts }; }
async function assertFinal(client: ReturnType<typeof createClient>, plan: PlanRow[]) { const ids = [...plan.map((row) => row.legacy_id), ...plan.map((row) => row.duplicate_id)]; const [{ data: cards, error: cardError }, { data: refs, error: refError }, { data: links, error: linkError }] = await Promise.all([client.from('cards_catalog').select('id,external_source,external_id,pokemon,set_name,set_code,number,rarity,image_small,image_large,card_details').in('id', ids), client.from('card_external_references').select('card_catalog_id,source,external_id').in('card_catalog_id', ids), client.from('collection_cards').select('card_catalog_id').in('card_catalog_id', plan.map((row) => row.legacy_id))]); if (cardError || refError || linkError) throw new Error('Herstelpostcheck mislukt.'); if ((cards?.length ?? 0) !== EXPECTED_PAIRS || (refs?.length ?? 0) !== EXPECTED_PAIRS || (links?.length ?? 0) !== EXPECTED_PAIRS) throw new Error('Herstelpostcheck heeft geen exacte aantallen.'); for (const row of plan) { const card = cards?.find((item) => item.id === row.legacy_id) as Card | undefined; const ref = refs?.find((item) => item.card_catalog_id === row.legacy_id) as Ref | undefined; if (!card || !ref || card.external_source !== SOURCE || card.external_id !== row.external_id || card.pokemon !== row.pokemon || card.set_name !== row.set_name || card.set_code !== row.set_code || card.number !== row.number || card.rarity !== row.rarity || card.image_small !== row.image_small || card.image_large !== row.image_large || canonical(card.card_details) !== canonical(row.card_details) || ref.source !== SOURCE || ref.external_id !== row.external_id) throw new Error(`${row.external_id}: herstelpostcheck wijkt af.`); }
}
async function main() { const options = parseArgs(process.argv.slice(2)); if (existsSync(options.reportPath)) throw new Error(`Rapport bestaat al: ${options.reportPath}`); const errors: string[] = []; let writes = 0; let plan: PlanRow[] = []; try { const url = process.env.SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) throw new Error('SUPABASE_URL en SUPABASE_SERVICE_ROLE_KEY ontbreken.'); const client = createClient(url, key); if (options.mode === 'idempotency') { const approved = readApproved(options.approvedReport!); plan = approved.repairPlan; await assertFinal(client, plan); } else { const state = await snapshot(client); plan = createRepairPlan(state.cards, state.refs, state.counts); const identity = { datasetVersion: PINNED_DATASET_VERSION, repairPlanHash: hash(plan), expectedPairs: EXPECTED_PAIRS, plannedDatabaseWrites: EXPECTED_PAIRS * 4 }; if (options.mode === 'write') { const approved = readApproved(options.approvedReport!); if (canonical(identity) !== canonical({ datasetVersion: approved.datasetVersion, repairPlanHash: approved.repairPlanHash, expectedPairs: approved.expectedPairs, plannedDatabaseWrites: approved.plannedDatabaseWrites }) || canonical(plan) !== canonical(approved.repairPlan)) throw new Error('Goedgekeurd herstelrapport hoort niet bij deze database-state.'); const { data, error } = await client.rpc('phase_7b_reconcile_safe_six_legacy_duplicates', { p_rows: plan }); const result = Array.isArray(data) ? data[0] as { cards_updated?: number; references_updated?: number; duplicate_cards_deleted?: number; duplicate_references_deleted?: number } : undefined; if (error || !result || result.cards_updated !== EXPECTED_PAIRS || result.references_updated !== EXPECTED_PAIRS || result.duplicate_cards_deleted !== EXPECTED_PAIRS || result.duplicate_references_deleted !== EXPECTED_PAIRS) throw new Error(`Transactioneel herstel mislukt: ${error?.message ?? 'ongeldige response'}`); writes = EXPECTED_PAIRS * 4; await assertFinal(client, plan); } }
  } catch (error) { errors.push(error instanceof Error ? error.message : 'Onbekende fout.'); }
  const report = writeReport(options.reportPath, { schemaVersion: 1, phase: 'Phase 7B recover six legacy duplicates', mode: options.mode, datasetVersion: PINNED_DATASET_VERSION, repairPlan: plan, repairPlanHash: hash(plan), expectedPairs: EXPECTED_PAIRS, plannedDatabaseWrites: EXPECTED_PAIRS * 4, databaseWritesTotal: writes, status: errors.length === 0 ? 'PASS' : 'FAIL', errors }); console.log(`Phase 7B recover six legacy duplicates ${report.mode}: ${report.status}; pairs=${report.expectedPairs}; databaseWritesTotal=${report.databaseWritesTotal}; reportHash=${report.reportHash}`); if (report.status === 'FAIL') process.exitCode = 1; }
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().catch((error) => { console.error(error instanceof Error ? error.message : 'Recovery runner failed.'); process.exitCode = 1; });
